export const items = [
  // Phones (1-10)
  {
      id: 1,
      category: 'mobiles',
      title: "Apple iPhone 14",
      imgSrc: 'https://m.media-amazon.com/images/I/61bK6PMOC3L._SX679_.jpg',
      amazonLink: 'https://amzn.to/3PuckZp',
      description: 'Apple iPhone 14 (128 GB) - Blue',
      price: '89999',
  },
  {
      id: 2,
      category: 'mobiles',
      title: "Apple iPhone 11",
      imgSrc: 'https://m.media-amazon.com/images/I/71QE00iB9IL._SX679_.jpg',
      amazonLink: 'https://amzn.to/44MiYi6',
      description: 'Apple iPhone 11 (64GB) - White',
      price: '79999',
  },
  {
      id: 3,
      category: 'mobiles',
      title: "Apple iPhone 13",
      imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r6XJtv',
      description: 'Apple iPhone 13 (128GB) - Blue',
      price: '69999',
  },
  {
      id: 4,
      category: 'mobiles',
      title: "Samsung Galaxy S23 Ultra",
      imgSrc: 'https://m.media-amazon.com/images/I/71OXmy3NMCL._SX679_.jpg',
      amazonLink: 'https://t.ly/gVbuO',
      description: 'Samsung Galaxy S23 Ultra (256GB) - Phantom Black',
      price: '124999',
  },
  {
      id: 5,
      category: 'mobiles',
      title: "OnePlus 11 5G",
      imgSrc: 'https://m.media-amazon.com/images/I/61amb0CfMGL._SX679_.jpg',
      amazonLink: 'https://t.ly/kAmpK',
      description: 'OnePlus 11 5G (128GB) - Eternal Green',
      price: '59999',
  },
  {
      id: 6,
      category: 'mobiles',
      title: "Vivo V29 Pro",
      imgSrc: 'https://m.media-amazon.com/images/I/71Ybh7jdwLL._SX679_.jpg',
      amazonLink: 'https://t.ly/q6v1d',
      description: 'Vivo V29 Pro (256GB) - Himalayan Blue',
      price: '44999',
  },
  {
      id: 7,
      category: 'mobiles',
      title: "Xiaomi Mi 13",
      imgSrc: 'https://m.media-amazon.com/images/I/81weRj535kL._SX679_.jpg',
      amazonLink: 'https://t.ly/Fy0qE',
      description: 'Xiaomi Mi 13 (128GB) - Graphite Grey',
      price: '52999',
  },
  {
      id: 8,
      category: 'mobiles',
      title: "Samsung Galaxy S22 5G",
      imgSrc: 'https://m.media-amazon.com/images/I/71wGLBDEsvL._SX679_.jpg',
      amazonLink: 'https://t.ly/Y2V7b',
      description: 'Samsung Galaxy S22 5G (Phantom Black, 8GB, 128GB Storage)',
      price: '36699',
  },
  {
      id: 9,
      category: 'mobiles',
      title: "Realme GT 2 Pro",
      imgSrc: 'https://m.media-amazon.com/images/I/61HyiMlCuTL._SX679_.jpg',
      amazonLink: 'https://t.ly/b5GOy',
      description: "realme GT 6T 5G (Fluid Silver,8GB RAM+256GB Storage) | India's 1st 7+ Gen 3 Flagship Chipset | 1.5M + AnTuTu Score | 5500mAh+120W | The World's Brightest Flagship Display",
      price: '47999',
  },
  {
      id: 10,
      category: 'mobiles',
      title: "Oppo Reno 10",
      imgSrc: 'https://m.media-amazon.com/images/I/71SgqjoTNzL._SX679_.jpg',
      amazonLink: 'https://t.ly/fqvOM',
      description: 'Oppo Reno 10 (128GB) - Aurora Blue',
      price: '34999',
  },

  // Laptops (11-20)
  {
      id: 11,
      category: 'laptops',
      title: "Xiaomi [Smartchoice] Notebookpro",
      imgSrc: 'https://m.media-amazon.com/images/I/71iiXU7HHkL._SX522_.jpg',
      amazonLink: 'https://amzn.to/3EzeQaC',
      description: 'Xiaomi [Smartchoice] Notebookpro',
      price: '49999',
  },
  {
      id: 12,
      category: 'laptops',
      title: "Lenovo IdeaPad Slim 5",
      imgSrc: 'https://m.media-amazon.com/images/I/61UjxQh+aYL._SX679_.jpg',
      amazonLink: 'https://amzn.to/44JsK4r',
      description: 'Lenovo IdeaPad Slim 5 Intel Core i5 12450H 14" (35.5cm)',
      price: '29999',
  },
  {
      id: 13,
      category: 'laptops',
      title: "Apple MacBook Air Laptop",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display',
      price: '89999',
  },
  {
      id: 14,
      category: 'laptops',
      title: "HP Pavilion x360",
      imgSrc: 'https://m.media-amazon.com/images/I/51OAoUHppPL._SX679_.jpg',
      amazonLink: 'https://t.ly/FwK2o',
      description: 'HP Pavilion x360 Core i5 13th Gen (16GB RAM/512GB SSD/FHD/Windows 11/MS Office/Touchscreen/5MP Camera/Backlit Keyboard/Audio by B&O/14” (35.6cm)/Silver/1.51kg) ek1074TU Laptop',
      price: '62999',
  },
  {
      id: 15,
      category: 'laptops',
      title: "Dell Inspiron 15",
      imgSrc: 'https://m.media-amazon.com/images/I/51Zl9TAM8kL._SX679_.jpg',
      amazonLink: 'https://t.ly/vGdGS',
      description: 'Dell Inspiron 15 (12th Gen i7, 16GB RAM, 1TB SSD) - Platinum Silver',
      price: '84999',
  },
  {
      id: 16,
      category: 'laptops',
      title: "Asus ZenBook Duo",
      imgSrc: 'https://m.media-amazon.com/images/I/71lkcGXb9cL._SX679_.jpg',
      amazonLink: 'https://t.ly/WvfHP',
      description: 'Asus ZenBook Duo (14-inch, 8GB RAM, 512GB SSD) - Celestial Blue',
      price: '75999',
  },
  {
      id: 17,
      category: 'laptops',
      title: "Acer Aspire 7",
      imgSrc: 'https://m.media-amazon.com/images/I/41LMzzdYO+L.jpg',
      amazonLink: 'https://t.ly/_E-aj',
      description: 'Acer Aspire 7 (15.6", 8GB, 512GB SSD) - Charcoal Black',
      price: '57999',
  },
  {
      id: 18,
      category: 'laptops',
      title: "MSI Modern 14",
      imgSrc: 'https://m.media-amazon.com/images/I/415FAC9suAL._SX300_SY300_QL70_FMwebp_.jpg',
      amazonLink: 'https://t.ly/h03DD',
      description: 'MSI Modern 14 (Intel i5, 8GB RAM, 256GB SSD) - Black',
      price: '51999',
  },
  {
      id: 19,
      category: 'laptops',
      title: "Samsung Galaxy Book 2 Pro",
      imgSrc: 'https://m.media-amazon.com/images/I/81aAFpuI1UL._SX522_.jpg',
      amazonLink: 'https://t.ly/iNnHY',
      description: 'Samsung Galaxy Book 2 Pro (13.3", Intel i7, 16GB RAM, 512GB SSD)',
      price: '96999',
  },
  {
      id: 20,
      category: 'laptops',
      title: "Huawei MateBook D 15",
      imgSrc: 'https://m.media-amazon.com/images/I/61-3l5x8Q+L._SX679_.jpg',
      amazonLink: 'https://t.ly/OPILb',
      description: 'Huawei MateBook D 15 (15.6", AMD Ryzen 5, 8GB, 256GB SSD) - Mystic Silver',
      price: '48999',
  },

  // Tablets (21-30)
  {
      id: 21,
      category: 'tablets',
      title: "Xiaomi Pad 6",
      imgSrc: 'https://m.media-amazon.com/images/I/41nIyVgOb-L._SX300_SY300_QL70_FMwebp_.jpg',
      amazonLink: 'https://amzn.to/3ZeNRdY',
      description: 'Xiaomi Pad 6| Qualcomm Snapdragon 870',
      price: '29999',
  },
  {
      id: 22,
      category: 'tablets',
      title: "Lenovo Tab P12 Pro AMOLED",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3RabsdH',
      description: 'Lenovo Tab P12 Pro AMOLED (12.6 inch (32 cm), 8 GB, 256 GB, Wi-fi Only)',
      price: '19999',
  },
  {
      id: 23,
      category: 'tablets',
      title: "Samsung Galaxy Tab A8",
      imgSrc: 'https://m.media-amazon.com/images/I/91veRYPjpeL._SX679_.jpg',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'Samsung Galaxy Tab A8 26.69cm (10.5 inch) Display, RAM 4 GB, ROM 64 GB Expandable',
      price: '49999',
  },
  {
      id: 24,
      category: 'tablets',
      title: "Apple iPad Air (5th Gen)",
      imgSrc: 'https://m.media-amazon.com/images/I/61JREs56sTL._SX679_.jpg',
      amazonLink: 'https://t.ly/lC3fp',
      description: 'Apple iPad Air (5th Gen) Wi-Fi 64GB - Space Grey',
      price: '54999',
  },
  {
    id: 25,
    category: 'tablets',
    title: "Realme Pad X",
    imgSrc: 'https://m.media-amazon.com/images/I/614ofbAkWxL._SX522_.jpg',
    amazonLink: 'https://t.ly/i6NaX',
    description: 'Realme Pad X (11 inch, 8GB RAM, 128GB Storage) - Glacier Blue',
    price: '25999',
  },
  {
    id: 26,
    category: 'tablets',
    title: "Microsoft Surface Pro 9",
    imgSrc: 'https://m.media-amazon.com/images/I/51+iKnnyQeL._SX679_.jpg',
    amazonLink: 'https://t.ly/v5Rlq',
    description: 'Microsoft Surface Pro 9 (13 inch, Intel i5, 8GB RAM, 128GB SSD)',
    price: '87999',
  },
  {
    id: 27,
    category: 'tablets',
    title: "Samsung Galaxy Tab S9 FE",
    imgSrc: 'https://m.media-amazon.com/images/I/61gVQJ5Yy0L._SX679_.jpg',
    amazonLink: 'https://t.ly/yAU2O',
    description: 'Samsung Galaxy Tab S9 FE 27.69 cm (10.9 inch) Display, RAM 6 GB, ROM 128 GB Expandable, S Pen in-Box, Wi-Fi, IP68 Tablet, Gray',
    price: '68999',
  },
  {
    id: 28,
    category: 'tablets',
    title: "Apple iPad Pro 11",
    imgSrc: 'https://m.media-amazon.com/images/I/61G6WfvA9vL._SX679_.jpg',
    amazonLink: 'https://t.ly/AnYtc',
    description: 'Apple iPad Pro 11 (M1, 128GB) - Silver',
    price: '74999',
  },
  {
    id: 29,
    category: 'tablets',
    title: "Redmi Pad Pro 5G",
    imgSrc: 'https://m.media-amazon.com/images/I/71jH01R-CgL._SX679_.jpg',
    amazonLink: 'https://t.ly/oRypw',
    description: 'Redmi Pad Pro 5G |Snapdragon 7s Gen 2|30.7cm(12.1") Tablet|33+ Days Standby| 10000mAh|HyperOS|8GB, 128GB|Quad Speakers |Wi-Fi 6 + 5G |Graphite Grey',
    price: '59999',
  },
  {
    id: 30,
    category: 'tablets',
    title: "Lenovo Tab M11",
    imgSrc: 'https://m.media-amazon.com/images/I/51fWpRMV-dL._SX679_.jpg',
    amazonLink: 'https://t.ly/lw-WN',
    description: 'Lenovo Tab M11 with Pen| Wi-Fi Connectivity| 8 Gb Ram, 128 Gb ROM|11 Inch Screen| 90 Hz, 72% Ntsc, Fhd Display| Quad Speakers with Dolby Atmos|Octa-Core Processor |13 Mp Rear Camera,White',
    price: '19999',
  },
];